#!/bin/python

#Begin imports
import os
import sys

#Check if options are put, tell user what to do if not
def leng(length):
	if len(opts) < length:
		sys.exit("Please use correct operators\nRun BossPhone with the operator \"-h\" to see correct operators")

opts = sys.argv[:]

ip = ""
passwd = ""
usr = ""

if len(opts) > 1:
	opt = opts[1]
else:
	print("Please input an operator\n")
	opt = "-h"

#Actions based on specific input
if opt == "-m":
	leng(3)
	os.system("sshpass -p \"" + passwd + "\" ssh " + usr + "@" + ip + " -p 8022 -t \"termux-toast \\\"" + opts[2] + "\\\"\"")
elif opt == "-s":
	leng(3)
	os.system("sshpass -p \"" + passwd + "\" ssh " + usr + "@" + ip + " -p 8022 -t \"termux-tts-speak \\\"" + opts[2] + "\\\"\"")
elif opt == "-t":
	leng(4)
	os.system("sshpass -p \"" + passwd + "\" ssh " + usr + "@" + ip + " -p 8022 -t \"termux-sms-send -n " + opts[2] + " \\\"" + opts[3] + "\\\"\"")
elif opt == "-p":
	leng(2)
	os.system("sshpass -p \"" + passwd + "\" ssh " + usr + "@" + ip + " -p 8022 -t \"termux-camera-photo ~/storage/pictures/$RANDOM.jpg\"")
elif opt == "-f":
	leng(3)
	os.system("sshpass -p \"" + passwd + "\" ssh " + usr + "@" + ip + " -p 8022 -t \"termux-torch \\\"" + opts[2] + "\\\"\"")
else:
	if opt != "-h":
		print(opt + " is not an operator")
	print("-h                    Print this help message\n-m message            Display message on screen of phone\n-s message            Use text-to-speach to say message\n-t number message     Send text message to specified number\n-p                    Take photo with phone's camera\n-f on/off             Turn flashlight on or off")
