#!/bin/python

#Begin imports
import os
import sys

#Check if options are put, tell user what to do if not
def leng(length):
	if len(opts) < length:
		sys.exit("Please use correct operators\nRun BossPhone with the operator \"-h\" to see correct operators")

opts = sys.argv[:]

creds = []
with open(".cred", "r") as f:
	creds = f.readlines()
	f.close()
creds = [cred[:-1] for cred in creds]

if len(creds) < 3:
        sys.exit("Please set device information\nRun BossPhone with the operator \"-i\" to see set device information\nRun BossPhone with the operator \"-h\" to see correct syntax")


usr = str(creds[0])
ip = str(creds[1])
passwd = str(creds[2])

if len(opts) > 1:
	opt = opts[1]
else:
	print("Please input an operator\n")
	opt = "-h"

#Actions based on specific input
if opt == "-m":
	leng(3)
	os.system("sshpass -p \"" + passwd + "\" ssh " + usr + "@" + ip + " -p 8022 -t \"termux-toast \\\"" + opts[2] + "\\\"\"")
elif opt == "-s":
	leng(3)
	os.system("sshpass -p \"" + passwd + "\" ssh " + usr + "@" + ip + " -p 8022 -t \"termux-tts-speak \\\"" + opts[2] + "\\\"\"")
elif opt == "-t":
	leng(4)
	os.system("sshpass -p \"" + passwd + "\" ssh " + usr + "@" + ip + " -p 8022 -t \"termux-sms-send -n " + opts[2] + " \\\"" + opts[3] + "\\\"\"")
elif opt == "-p":
	leng(2)
	os.system("sshpass -p \"" + passwd + "\" ssh " + usr + "@" + ip + " -p 8022 -t \"termux-camera-photo ~/storage/pictures/$RANDOM.jpg\"")
elif opt == "-f":
	leng(3)
	os.system("sshpass -p \"" + passwd + "\" ssh " + usr + "@" + ip + " -p 8022 -t \"termux-torch \\\"" + opts[2] + "\\\"\"")
elif opt == "-c":
	leng(3)
	os.system("sshpass -p \"" + passwd + "\" ssh " + usr + "@" + ip + " -p 8022 -t \"termux-telephony-call \\\"" + opts[2] + "\\\"\"")
elif opt == "-i":
	leng(5)
	os.system("echo \"" + opts[2] + "\" > .cred")
	os.system("echo \"" + opts[3] + "\" >> .cred")
	os.system("echo \"" + opts[4] + "\" >> .cred")
else:
	if opt != "-h":
		print(opt + " is not an operator")
	print("-h                        Print this help message")
	print("-m message                Display message on screen of phone")
	print("-s message                Use text-to-speach to say message")
	print("-t number message         Send text message to specified number")
	print("-p                        Take photo with phone's camera")
	print("-f on/off                 Turn flashlight on or off")
	print("-c number                 Call a specified number")
	print("-i username ip password   Set user information")
